version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /cli
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /controller
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /controller
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /workspace
    schedule:
      interval: weekly
