apiVersion: v1
kind: Service
metadata:
  name: {{ include "devboxes.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devboxes.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "devboxes.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
